### PR TITLE
Update `prefs.js` to match cosmic and dock version

### PR DESCRIPTION
**Pull request by ids1024**

### CODE REVIEW

**Comment by jacobgkau** [comment]
If I open this dialog for both multi-monitors and the dock at the same time, the `Configure in Settings` button on whichever one I opened first stops working and causes the window to freeze. The same thing happens if I open multiple copies of the multi-monitors panel or multiple copies of the dock panel. Is that something that could be fixed easily, or is it a larger issue with extension settings panels in GNOME?

**Comment by jackpot51** [comment]
Is appinfo.launch async? That might be the issue

**Comment by jackpot51** [comment]
Okay, this is happening with just opening the cosmic dock settings. Very strange

**Comment by ids1024** [comment]
Weird. I seem to see the same thing with two random extensions that aren't ours (opening the preferences for both, the first becomes impossible to interact with). So I guess an upstream issue.

**Comment by jackpot51** [comment]
Yeah, I'm okay to merge and address later

**Comment by jackpot51** [comment]
@jacobgkau any other issues?

**Review by jacobgkau — APPROVED** [review]
That's fine. The dialog is otherwise looking and working correctly.

**Comment by jacobgkau** [comment]
Opened an issue here to track it, in case anyone notices: https://github.com/pop-os/gnome-shell-extension-multi-monitors/issues/6

**Pull request merged**
